connect/urls.py
from django.urls import path
from django.urls import path,include


from . import views

app_name  = 'connect'
urlpatterns = [
    path('',views.base_index,name='base_index'),
]

matches/urls.py
from django.urls import path
from . import views

app_name = 'matches'

urlpatterns = [
    path('',views.create,name='create'),
    path('create/', views.import_csv, name='import_csv'),
    path('dict/',views.makeDictionary,name='makeDictionary'),
    path('won/',views.matchesWon,name='matchesWon')
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('connect.urls')),
    path('matches/', include('matches.urls')),
    path('schools/', include('schools.urls')),
]

schools/urls.py
from django.urls import path

from . import views

app_name = 'schools'
urlpatterns = [
     path('',views.create,name='create'),
    path('create/', views.import_csv, name='import_csv'),
    path('dict/',views.makeDictionary,name='makeDictionary'),
    path('cat/',views.schholCategory,name = 'schholCategory'),
    path('lang/',views.lamguageDist,name = 'lamguageDist'),
]

connect/models.py
from django.db import models

# Create your models here.

matches/models.py
from django.db import models

# Create your models here.

class MatchModel(models.Model):
    year = models.CharField(max_length=200)
    winner = models.CharField(max_length=200)
   

schools/models.py
from django.db import models

class School(models.Model):
    name = models.CharField(max_length=255)
    district = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    language = models.CharField(max_length=255)

connect/views.py
from django.shortcuts import render

def base_index(request):
    return render(request, "connect/base_index.html")

matches/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import MatchModel
from django.http import JsonResponse
from django.db.models import Count
import csv
import json
from django.core.serializers import serialize



def create(request):
    return render(request,'matches/createData.html')         


def import_csv(request):
    str="Data Alredy Exist"
    if request.method=='POST' and 'import_csv' in request.POST:    
        if not MatchModel.objects.exists(): 
            file_path = r'/Users/kaushiknandan/Desktop/python/kaushik/matches - matches.csv'
            with open(file_path) as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    MatchModel.objects.create(
                        year=row['season'],
                        winner = row['winner']
                    )
            str="Data Created"        
            return render(request,'matches/first.html',{'str':str})   
        else:
            return render(request,'matches/first.html',{'str':str})     
    
           

def makeDictionary(request):
    if request.method == 'POST' and 'make_dictionary' in request.POST:    
        matches_per_season = MatchModel.objects.values('year').annotate(matches_played=Count('id')).order_by('year')
        match_list=list(matches_per_season)  
        context  = {"matches":match_list}        
        return render(request,'matches/display.html',context)



def matchesWon(request):
    if request.method == 'POST' and 'matches_won' in request.POST:    
        matches_won = MatchModel.objects.values('year','winner').annotate(matches_won = Count('id'))
        matches_won_list = list(matches_won)
        context = {"matches":matches_won_list}
        return render(request,'matches/matches_won.html',context)

schools/views.py
from django.shortcuts import render
from .models import School
from django.http import HttpResponse
import csv
from django.db.models import Count



def create(request):
    return render(request,'schools/import_data.html')         


def import_csv(request):
    if request.method=='POST' and 'import_dataVal' in request.POST:    
        str='Data Alredy Present'
        if not School.objects.exists():    
            file_path = r'/Users/kaushiknandan/Desktop/python/kaushik/primaryschool - primaryschool.csv'
            with open(file_path) as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    School.objects.create(
                    name = row['name'],
                    district = row['district_name'],
                    category = row['cat'],
                    language = row['moi']

                    )
            str = "Data Created"         
            return render(request,'schools/first.html',{'str':str})  
        else:
            return render(request,'schools/first.html',{'str':str}) 

def makeDictionary(request):
    if request.method=='POST' and 'make_dictionary' in request.POST:        
        school_per_district = School.objects.values('district').annotate(count_of_schools=Count('id'))
        school_per_district_list = list(school_per_district)
        context  = {"schools":school_per_district_list}        
        return render(request,'schools/display.html',context)

def schholCategory(request):
    if request.method=='POST' and 'category' in request.POST:        
        schoolcat = School.objects.values('district','category').annotate(count_of_school = Count('id'))
        schoolcatlist = list(schoolcat)
        print(schoolcatlist)
        context = {"schools":schoolcatlist}
        return render(request,'schools/category.html',context)


def lamguageDist(request):
    if request.method=='POST' and 'lanng' in request.POST:        
        schoolcat = School.objects.values('district','language') .annotate(count_of_lang = Count('id'))
        schoolcatlist = list(schoolcat)
        print(schoolcatlist)
        context = {"schools":schoolcatlist}
        return render(request,'schools/lang.html',context)

connect/templates/connect/base_index.html
<!DOCTYPE html>
<html>
<head>
    <title>My Django Project</title>
</head>
<body>
    <h1>Welcome to My Django Project!</h1>
    
    <div>
        <a href="{% url 'matches:create' %}"><button>Go to Matches</button></a>
        <a href="{% url 'schools:create' %}"><button>Go to Schools</button></a>
    </div>
</body>
</html>

matches/templates/matches/createData.html
<html>
<head>
    <title>Match</title>
</head>
<body>
    <h1>IPL Matches</h1>
    
    <form method="post" >
        {% csrf_token %}
        <input type="submit" name="import_csv" value="import Data" formaction="{% url 'matches:import_csv' %}">
        <input type="submit" name="make_dictionary" value="Matches Played" formaction="{% url 'matches:makeDictionary' %}">
        <input type="submit" name="matches_won" value="Matches Won" formaction="{% url 'matches:matchesWon' %}">
        
    </form>

</body>
</html>

matches/templates/matches/display.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Match Data</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>Match Data</h1>

    <button onclick="goBack()">Go Back</button>
    <br>
    <br>

    <canvas id="myChart" width="400" height="200"></canvas>

    <script>
        
        var matchesData  = {{matches|safe}};
        console.log(matchesData);  
    
        var ssn = matchesData.map(function(item){
            return item.year;
        });
    
        var matchPlay = matchesData.map(function(item){
            return item.matches_played;
        });
    
        var ctx = document.getElementById('myChart').getContext('2d');
    
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ssn,
                datasets: [{
                    label: 'Number of Matches',
                    data: matchPlay,
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

        function goBack() {
           
            window.history.go(-1);
        }
    </script>
    
</body>
</html>

matches/templates/matches/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Match</title>
</head>
<body>
    <h1>{{str}}</h1>
    <button onclick="goBack()">Go back</button>

    <script>
        function goBack() {
           
            window.history.go(-1);
        }
    </script>
</body>
</html>

matches/templates/matches/matches_won.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Matches Won Per Season</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>Matches Won Per Season</h1>

<button onclick="goBack()">Go Back</button>
    <br>
    <br>

    <canvas id="matchesWonChart" width="400" height="200"></canvas>

    <script>
        
        var matchesData = {{ matches|safe }};

        
        var seasons = [...new Set(matchesData.map(item => item.year))];
        var teams = [...new Set(matchesData.map(item => item.winner))];
        var data = {};

       
        var teamColors = [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 0, 0, 0.2)',
            'rgba(0, 255, 0, 0.2)',
            'rgba(0, 0, 255, 0.2)',
            'rgba(128, 0, 128, 0.2)',
            'rgba(255, 140, 0, 0.2)',
            'rgba(128, 128, 0, 0.2)',
            'rgba(0, 128, 128, 0.2)',
            'rgba(128, 0, 0, 0.2)',
            'rgba(0, 128, 0, 0.2)',
        ];

       
        seasons.forEach(season => {
            data[season] = {};
            teams.forEach((team, index) => {
                data[season][team] = {
                    totalMatches: 0,
                    color: teamColors[index],
                };
            });
        });

       
        matchesData.forEach(item => {
            data[item.year][item.winner].totalMatches = item.matches_won;
        });


        document.addEventListener('DOMContentLoaded', function() {
            var ctx = document.getElementById('matchesWonChart').getContext('2d');
            var matchesWonChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: seasons,
                    datasets: teams.map((team, index) => ({
                        label: team,
                        data: seasons.map(season => data[season][team].totalMatches),
                        backgroundColor: teamColors[index],
                        borderColor: 'rgba(255, 255, 255, 0)', // Transparent border
                        borderWidth: 1
                    }))
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true,
                            stacked: true,
                            title: {
                                display: true,
                                text: 'Matches Won'
                            }
                        },
                        x: {
                            stacked: true,
                            title: {
                                display: true,
                                text: 'Season'
                            }
                        }
                    }
                }
            });
        });

        function goBack() {
           
            window.history.go(-1);
        }
    </script>
</body>
</html>

schools/templates/schools/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Schools</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>Schools per district</h1>
     <button onclick="goBack()" >Go Back</button>
    <canvas id="matchesWonChart" width="400" height="200"></canvas>

    <script>
      
        var schoolData = {{ schools|safe }};

     
        var dist = [...new Set(schoolData.map(item => item.district))];
        var cat = [...new Set(schoolData.map(item => item.category))];
        var data={}
      
        var teamColors = [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 0, 0, 0.2)',
            'rgba(0, 255, 0, 0.2)',
            'rgba(0, 0, 255, 0.2)',
            'rgba(128, 0, 128, 0.2)',
            'rgba(255, 140, 0, 0.2)',
            'rgba(128, 128, 0, 0.2)',
            'rgba(0, 128, 128, 0.2)',
            'rgba(128, 0, 0, 0.2)',
            'rgba(0, 128, 0, 0.2)',
        ];

      
        dist.forEach(dist => {
            data[dist] = {};
            cat.forEach((cat, index) => {
                data[dist][cat] = {
                    totalSchools: 0,
                    color: teamColors[index],
                };
            });
        });
       
      
        schoolData.forEach(item => {
            data[item.district][item.category].totalSchools = item.count_of_school
        });

        document.addEventListener('DOMContentLoaded', function() {
            var ctx = document.getElementById('matchesWonChart').getContext('2d');
            var matchesWonChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: dist,
                    datasets: cat.map((cat, index) => ({
                        label: cat,
                        data: dist.map(dist => data[dist][cat].totalSchools),
                        backgroundColor: teamColors[index],
                        borderColor: 'rgba(255, 255, 255, 0)', 
                        borderWidth: 1
                    }))
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true,
                            stacked: true,
                            title: {
                                display: true,
                                text: 'Schools '
                            }
                        },
                        x: {
                            stacked: true,
                            title: {
                                display: true,
                                text: 'District'
                            }
                        }
                    }
                }
            });
        });

        function goBack(){
            window.history.go(-1)
        }
    </script>
</body>
</html>

schools/templates/schools/display.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Total Schools</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>School Data</h1>
    <button onclick="goBack()" >Go back</button> 
    <canvas id="myChart" width="400" height="200"></canvas>

    <script>
        
        var schoolsData  = {{schools|safe}};
          
    
        var district = schoolsData.map(function(item){
            return item.district;
        });
    
        var count_of_schools = schoolsData.map(function(item){
            return item.count_of_schools;
        });
    
        var ctx = document.getElementById('myChart').getContext('2d');
    
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: district,
                datasets: [{
                    label: 'Number of Schools',
                    data: count_of_schools,
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

        function goBack()
        {
            window.history.go(-1)
        }
    </script>
    
</body>
</html>

schools/templates/schools/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Schools</title>
</head>
<body>
    <h1>{{str}}</h1>
    <button onclick="goBack()">Go back</button>
    <script>
        function goBack(){
            window.history.go(-1);
        }
    </script>
</body>
</html>

schools/templates/schools/import_data.html
<html>
  <head>
      <title>Schools</title>
  </head>
  <body>
      <h1>School Data</h1>
      
      <form method="post" >
          {% csrf_token %}
          <input type="submit" name="import_dataVal" value="import Data" formaction="{% url 'schools:import_csv' %}">
          <input type="submit" name="make_dictionary" value="Total School" formaction="{% url 'schools:makeDictionary' %}">
          <input type="submit" name="category" value="School category" formaction="{% url 'schools:schholCategory' %}">
          <input type="submit" name="lanng" value="Languages per District" formaction="{% url 'schools:lamguageDist' %}">
          
      </form>
  
  </body>
  </html>

schools/templates/schools/lang.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Languages</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>Languages per district</h1>
    <button onclick="goBack()" >Go back</button>
    <canvas id="matchesWonChart" width="400" height="200"></canvas>

    <script>
      
        var schoolData = {{ schools|safe }};

        var dist = [...new Set(schoolData.map(item => item.district))];
        var cat = [...new Set(schoolData.map(item => item.language))];
        var data = {};

        var teamColors = [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 0, 0, 0.2)',
            'rgba(0, 255, 0, 0.2)',
            'rgba(0, 0, 255, 0.2)',
            'rgba(128, 0, 128, 0.2)',
            'rgba(255, 140, 0, 0.2)',
            'rgba(128, 128, 0, 0.2)',
            'rgba(0, 128, 128, 0.2)',
            'rgba(128, 0, 0, 0.2)',
            'rgba(0, 128, 0, 0.2)',
        ];

        dist.forEach(dist => {
            data[dist] = {};
            cat.forEach((cat, index) => {
                data[dist][cat] = {
                    totalSchools: 0,
                    color: teamColors[index],
                };
            });
        });

        schoolData.forEach(item => {
            data[item.district][item.language].totalSchools = item.count_of_lang
        });

        document.addEventListener('DOMContentLoaded', function() {
            var ctx = document.getElementById('matchesWonChart').getContext('2d');
            var matchesWonChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: dist,
                    datasets: cat.map((cat, index) => ({
                        label: cat,
                        data: dist.map(dist => data[dist][cat].totalSchools),
                        backgroundColor: teamColors[index],
                        borderColor: 'rgba(255, 255, 255, 0)', 
                        borderWidth: 1
                    }))
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true,
                            stacked: true,
                            title: {
                                display: true,
                                text: 'Schools '
                            }
                        },
                        x: {
                            stacked: true,
                            title: {
                                display: true,
                                text: 'Language'
                            }
                        }
                    }
                }
            });
        });

        function goBack(){
            window.history.go(-1)
        }
    </script>
</body>
</html>